#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTaiTotNghiep
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLdeTaiDoAnTotNghiep")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDeTaiDoAn(DeTaiDoAn instance);
    partial void UpdateDeTaiDoAn(DeTaiDoAn instance);
    partial void DeleteDeTaiDoAn(DeTaiDoAn instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertHoiDongBaoVe(HoiDongBaoVe instance);
    partial void UpdateHoiDongBaoVe(HoiDongBaoVe instance);
    partial void DeleteHoiDongBaoVe(HoiDongBaoVe instance);
    partial void InsertHoiDongBaoVe_GiangVien(HoiDongBaoVe_GiangVien instance);
    partial void UpdateHoiDongBaoVe_GiangVien(HoiDongBaoVe_GiangVien instance);
    partial void DeleteHoiDongBaoVe_GiangVien(HoiDongBaoVe_GiangVien instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertLichBaoVe(LichBaoVe instance);
    partial void UpdateLichBaoVe(LichBaoVe instance);
    partial void DeleteLichBaoVe(LichBaoVe instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QuanLyDeTaiTotNghiep.Properties.Settings.Default.QLdeTaiDoAnTotNghiepConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DeTaiDoAn> DeTaiDoAns
		{
			get
			{
				return this.GetTable<DeTaiDoAn>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<HoiDongBaoVe> HoiDongBaoVes
		{
			get
			{
				return this.GetTable<HoiDongBaoVe>();
			}
		}
		
		public System.Data.Linq.Table<HoiDongBaoVe_GiangVien> HoiDongBaoVe_GiangViens
		{
			get
			{
				return this.GetTable<HoiDongBaoVe_GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<LichBaoVe> LichBaoVes
		{
			get
			{
				return this.GetTable<LichBaoVe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeTaiDoAn")]
	public partial class DeTaiDoAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detai;
		
		private string _ten_detai;
		
		private EntitySet<SinhVien> _SinhViens;
		
		private EntitySet<LichBaoVe> _LichBaoVes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detaiChanging(int value);
    partial void Onid_detaiChanged();
    partial void Onten_detaiChanging(string value);
    partial void Onten_detaiChanged();
    #endregion
		
		public DeTaiDoAn()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			this._LichBaoVes = new EntitySet<LichBaoVe>(new Action<LichBaoVe>(this.attach_LichBaoVes), new Action<LichBaoVe>(this.detach_LichBaoVes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detai
		{
			get
			{
				return this._id_detai;
			}
			set
			{
				if ((this._id_detai != value))
				{
					this.Onid_detaiChanging(value);
					this.SendPropertyChanging();
					this._id_detai = value;
					this.SendPropertyChanged("id_detai");
					this.Onid_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_detai", DbType="VarChar(255)")]
		public string ten_detai
		{
			get
			{
				return this._ten_detai;
			}
			set
			{
				if ((this._ten_detai != value))
				{
					this.Onten_detaiChanging(value);
					this.SendPropertyChanging();
					this._ten_detai = value;
					this.SendPropertyChanged("ten_detai");
					this.Onten_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTaiDoAn_SinhVien", Storage="_SinhViens", ThisKey="id_detai", OtherKey="id_detai")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTaiDoAn_LichBaoVe", Storage="_LichBaoVes", ThisKey="id_detai", OtherKey="id_detai")]
		public EntitySet<LichBaoVe> LichBaoVes
		{
			get
			{
				return this._LichBaoVes;
			}
			set
			{
				this._LichBaoVes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.DeTaiDoAn = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.DeTaiDoAn = null;
		}
		
		private void attach_LichBaoVes(LichBaoVe entity)
		{
			this.SendPropertyChanging();
			entity.DeTaiDoAn = this;
		}
		
		private void detach_LichBaoVes(LichBaoVe entity)
		{
			this.SendPropertyChanging();
			entity.DeTaiDoAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sinhvien;
		
		private string _ho_ten;
		
		private string _lop;
		
		private string _ma_sv;
		
		private System.Nullable<double> _diem;
		
		private System.Nullable<int> _id_detai;
		
		private System.Nullable<int> _id_khoa;
		
		private EntityRef<DeTaiDoAn> _DeTaiDoAn;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sinhvienChanging(int value);
    partial void Onid_sinhvienChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    partial void Onma_svChanging(string value);
    partial void Onma_svChanged();
    partial void OndiemChanging(System.Nullable<double> value);
    partial void OndiemChanged();
    partial void Onid_detaiChanging(System.Nullable<int> value);
    partial void Onid_detaiChanged();
    partial void Onid_khoaChanging(System.Nullable<int> value);
    partial void Onid_khoaChanged();
    #endregion
		
		public SinhVien()
		{
			this._DeTaiDoAn = default(EntityRef<DeTaiDoAn>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sinhvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sinhvien
		{
			get
			{
				return this._id_sinhvien;
			}
			set
			{
				if ((this._id_sinhvien != value))
				{
					this.Onid_sinhvienChanging(value);
					this.SendPropertyChanging();
					this._id_sinhvien = value;
					this.SendPropertyChanged("id_sinhvien");
					this.Onid_sinhvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="VarChar(255)")]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="VarChar(50)")]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_sv", DbType="VarChar(50)")]
		public string ma_sv
		{
			get
			{
				return this._ma_sv;
			}
			set
			{
				if ((this._ma_sv != value))
				{
					this.Onma_svChanging(value);
					this.SendPropertyChanging();
					this._ma_sv = value;
					this.SendPropertyChanged("ma_sv");
					this.Onma_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Float")]
		public System.Nullable<double> diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detai", DbType="Int")]
		public System.Nullable<int> id_detai
		{
			get
			{
				return this._id_detai;
			}
			set
			{
				if ((this._id_detai != value))
				{
					if (this._DeTaiDoAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_detaiChanging(value);
					this.SendPropertyChanging();
					this._id_detai = value;
					this.SendPropertyChanged("id_detai");
					this.Onid_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khoa", DbType="Int")]
		public System.Nullable<int> id_khoa
		{
			get
			{
				return this._id_khoa;
			}
			set
			{
				if ((this._id_khoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khoaChanging(value);
					this.SendPropertyChanging();
					this._id_khoa = value;
					this.SendPropertyChanged("id_khoa");
					this.Onid_khoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTaiDoAn_SinhVien", Storage="_DeTaiDoAn", ThisKey="id_detai", OtherKey="id_detai", IsForeignKey=true)]
		public DeTaiDoAn DeTaiDoAn
		{
			get
			{
				return this._DeTaiDoAn.Entity;
			}
			set
			{
				DeTaiDoAn previousValue = this._DeTaiDoAn.Entity;
				if (((previousValue != value) 
							|| (this._DeTaiDoAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeTaiDoAn.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._DeTaiDoAn.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._id_detai = value.id_detai;
					}
					else
					{
						this._id_detai = default(Nullable<int>);
					}
					this.SendPropertyChanged("DeTaiDoAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_Khoa", ThisKey="id_khoa", OtherKey="id_khoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._id_khoa = value.id_khoa;
					}
					else
					{
						this._id_khoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_giangvien;
		
		private string _ten_giangvien;
		
		private string _ma_giangvien;
		
		private EntitySet<HoiDongBaoVe_GiangVien> _HoiDongBaoVe_GiangViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_giangvienChanging(int value);
    partial void Onid_giangvienChanged();
    partial void Onten_giangvienChanging(string value);
    partial void Onten_giangvienChanged();
    partial void Onma_giangvienChanging(string value);
    partial void Onma_giangvienChanged();
    #endregion
		
		public GiangVien()
		{
			this._HoiDongBaoVe_GiangViens = new EntitySet<HoiDongBaoVe_GiangVien>(new Action<HoiDongBaoVe_GiangVien>(this.attach_HoiDongBaoVe_GiangViens), new Action<HoiDongBaoVe_GiangVien>(this.detach_HoiDongBaoVe_GiangViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_giangvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_giangvien
		{
			get
			{
				return this._id_giangvien;
			}
			set
			{
				if ((this._id_giangvien != value))
				{
					this.Onid_giangvienChanging(value);
					this.SendPropertyChanging();
					this._id_giangvien = value;
					this.SendPropertyChanged("id_giangvien");
					this.Onid_giangvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_giangvien", DbType="VarChar(255)")]
		public string ten_giangvien
		{
			get
			{
				return this._ten_giangvien;
			}
			set
			{
				if ((this._ten_giangvien != value))
				{
					this.Onten_giangvienChanging(value);
					this.SendPropertyChanging();
					this._ten_giangvien = value;
					this.SendPropertyChanged("ten_giangvien");
					this.Onten_giangvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_giangvien", DbType="VarChar(50)")]
		public string ma_giangvien
		{
			get
			{
				return this._ma_giangvien;
			}
			set
			{
				if ((this._ma_giangvien != value))
				{
					this.Onma_giangvienChanging(value);
					this.SendPropertyChanging();
					this._ma_giangvien = value;
					this.SendPropertyChanged("ma_giangvien");
					this.Onma_giangvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_HoiDongBaoVe_GiangVien", Storage="_HoiDongBaoVe_GiangViens", ThisKey="id_giangvien", OtherKey="id_giangvien")]
		public EntitySet<HoiDongBaoVe_GiangVien> HoiDongBaoVe_GiangViens
		{
			get
			{
				return this._HoiDongBaoVe_GiangViens;
			}
			set
			{
				this._HoiDongBaoVe_GiangViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoiDongBaoVe_GiangViens(HoiDongBaoVe_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_HoiDongBaoVe_GiangViens(HoiDongBaoVe_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoiDongBaoVe")]
	public partial class HoiDongBaoVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoidong;
		
		private string _ten_hoidong;
		
		private EntitySet<HoiDongBaoVe_GiangVien> _HoiDongBaoVe_GiangViens;
		
		private EntitySet<LichBaoVe> _LichBaoVes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoidongChanging(int value);
    partial void Onid_hoidongChanged();
    partial void Onten_hoidongChanging(string value);
    partial void Onten_hoidongChanged();
    #endregion
		
		public HoiDongBaoVe()
		{
			this._HoiDongBaoVe_GiangViens = new EntitySet<HoiDongBaoVe_GiangVien>(new Action<HoiDongBaoVe_GiangVien>(this.attach_HoiDongBaoVe_GiangViens), new Action<HoiDongBaoVe_GiangVien>(this.detach_HoiDongBaoVe_GiangViens));
			this._LichBaoVes = new EntitySet<LichBaoVe>(new Action<LichBaoVe>(this.attach_LichBaoVes), new Action<LichBaoVe>(this.detach_LichBaoVes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoidong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hoidong
		{
			get
			{
				return this._id_hoidong;
			}
			set
			{
				if ((this._id_hoidong != value))
				{
					this.Onid_hoidongChanging(value);
					this.SendPropertyChanging();
					this._id_hoidong = value;
					this.SendPropertyChanged("id_hoidong");
					this.Onid_hoidongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_hoidong", DbType="NVarChar(255)")]
		public string ten_hoidong
		{
			get
			{
				return this._ten_hoidong;
			}
			set
			{
				if ((this._ten_hoidong != value))
				{
					this.Onten_hoidongChanging(value);
					this.SendPropertyChanging();
					this._ten_hoidong = value;
					this.SendPropertyChanged("ten_hoidong");
					this.Onten_hoidongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoiDongBaoVe_HoiDongBaoVe_GiangVien", Storage="_HoiDongBaoVe_GiangViens", ThisKey="id_hoidong", OtherKey="id_hoidong")]
		public EntitySet<HoiDongBaoVe_GiangVien> HoiDongBaoVe_GiangViens
		{
			get
			{
				return this._HoiDongBaoVe_GiangViens;
			}
			set
			{
				this._HoiDongBaoVe_GiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoiDongBaoVe_LichBaoVe", Storage="_LichBaoVes", ThisKey="id_hoidong", OtherKey="id_hoidong")]
		public EntitySet<LichBaoVe> LichBaoVes
		{
			get
			{
				return this._LichBaoVes;
			}
			set
			{
				this._LichBaoVes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoiDongBaoVe_GiangViens(HoiDongBaoVe_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.HoiDongBaoVe = this;
		}
		
		private void detach_HoiDongBaoVe_GiangViens(HoiDongBaoVe_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.HoiDongBaoVe = null;
		}
		
		private void attach_LichBaoVes(LichBaoVe entity)
		{
			this.SendPropertyChanging();
			entity.HoiDongBaoVe = this;
		}
		
		private void detach_LichBaoVes(LichBaoVe entity)
		{
			this.SendPropertyChanging();
			entity.HoiDongBaoVe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoiDongBaoVe_GiangVien")]
	public partial class HoiDongBaoVe_GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_HoiDongBaoVe_GiangVien;
		
		private System.Nullable<int> _id_hoidong;
		
		private System.Nullable<int> _id_giangvien;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<HoiDongBaoVe> _HoiDongBaoVe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_HoiDongBaoVe_GiangVienChanging(int value);
    partial void Onid_HoiDongBaoVe_GiangVienChanged();
    partial void Onid_hoidongChanging(System.Nullable<int> value);
    partial void Onid_hoidongChanged();
    partial void Onid_giangvienChanging(System.Nullable<int> value);
    partial void Onid_giangvienChanged();
    #endregion
		
		public HoiDongBaoVe_GiangVien()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			this._HoiDongBaoVe = default(EntityRef<HoiDongBaoVe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_HoiDongBaoVe_GiangVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_HoiDongBaoVe_GiangVien
		{
			get
			{
				return this._id_HoiDongBaoVe_GiangVien;
			}
			set
			{
				if ((this._id_HoiDongBaoVe_GiangVien != value))
				{
					this.Onid_HoiDongBaoVe_GiangVienChanging(value);
					this.SendPropertyChanging();
					this._id_HoiDongBaoVe_GiangVien = value;
					this.SendPropertyChanged("id_HoiDongBaoVe_GiangVien");
					this.Onid_HoiDongBaoVe_GiangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoidong", DbType="Int")]
		public System.Nullable<int> id_hoidong
		{
			get
			{
				return this._id_hoidong;
			}
			set
			{
				if ((this._id_hoidong != value))
				{
					if (this._HoiDongBaoVe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hoidongChanging(value);
					this.SendPropertyChanging();
					this._id_hoidong = value;
					this.SendPropertyChanged("id_hoidong");
					this.Onid_hoidongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_giangvien", DbType="Int")]
		public System.Nullable<int> id_giangvien
		{
			get
			{
				return this._id_giangvien;
			}
			set
			{
				if ((this._id_giangvien != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_giangvienChanging(value);
					this.SendPropertyChanging();
					this._id_giangvien = value;
					this.SendPropertyChanged("id_giangvien");
					this.Onid_giangvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_HoiDongBaoVe_GiangVien", Storage="_GiangVien", ThisKey="id_giangvien", OtherKey="id_giangvien", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.HoiDongBaoVe_GiangViens.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.HoiDongBaoVe_GiangViens.Add(this);
						this._id_giangvien = value.id_giangvien;
					}
					else
					{
						this._id_giangvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoiDongBaoVe_HoiDongBaoVe_GiangVien", Storage="_HoiDongBaoVe", ThisKey="id_hoidong", OtherKey="id_hoidong", IsForeignKey=true)]
		public HoiDongBaoVe HoiDongBaoVe
		{
			get
			{
				return this._HoiDongBaoVe.Entity;
			}
			set
			{
				HoiDongBaoVe previousValue = this._HoiDongBaoVe.Entity;
				if (((previousValue != value) 
							|| (this._HoiDongBaoVe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoiDongBaoVe.Entity = null;
						previousValue.HoiDongBaoVe_GiangViens.Remove(this);
					}
					this._HoiDongBaoVe.Entity = value;
					if ((value != null))
					{
						value.HoiDongBaoVe_GiangViens.Add(this);
						this._id_hoidong = value.id_hoidong;
					}
					else
					{
						this._id_hoidong = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoiDongBaoVe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_khoa;
		
		private string _nam;
		
		private EntitySet<SinhVien> _SinhViens;
		
		private EntitySet<LichBaoVe> _LichBaoVes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_khoaChanging(int value);
    partial void Onid_khoaChanged();
    partial void OnnamChanging(string value);
    partial void OnnamChanged();
    #endregion
		
		public Khoa()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			this._LichBaoVes = new EntitySet<LichBaoVe>(new Action<LichBaoVe>(this.attach_LichBaoVes), new Action<LichBaoVe>(this.detach_LichBaoVes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_khoa
		{
			get
			{
				return this._id_khoa;
			}
			set
			{
				if ((this._id_khoa != value))
				{
					this.Onid_khoaChanging(value);
					this.SendPropertyChanging();
					this._id_khoa = value;
					this.SendPropertyChanged("id_khoa");
					this.Onid_khoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="NVarChar(255)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_SinhViens", ThisKey="id_khoa", OtherKey="id_khoa")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_LichBaoVe", Storage="_LichBaoVes", ThisKey="id_khoa", OtherKey="id_khoa")]
		public EntitySet<LichBaoVe> LichBaoVes
		{
			get
			{
				return this._LichBaoVes;
			}
			set
			{
				this._LichBaoVes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_LichBaoVes(LichBaoVe entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_LichBaoVes(LichBaoVe entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichBaoVe")]
	public partial class LichBaoVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lich;
		
		private string _phong;
		
		private System.Nullable<System.DateTime> _ngay;
		
		private System.Nullable<System.TimeSpan> _gio;
		
		private System.Nullable<int> _id_hoidong;
		
		private System.Nullable<int> _id_detai;
		
		private System.Nullable<int> _id_khoa;
		
		private EntityRef<DeTaiDoAn> _DeTaiDoAn;
		
		private EntityRef<HoiDongBaoVe> _HoiDongBaoVe;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lichChanging(int value);
    partial void Onid_lichChanged();
    partial void OnphongChanging(string value);
    partial void OnphongChanged();
    partial void OnngayChanging(System.Nullable<System.DateTime> value);
    partial void OnngayChanged();
    partial void OngioChanging(System.Nullable<System.TimeSpan> value);
    partial void OngioChanged();
    partial void Onid_hoidongChanging(System.Nullable<int> value);
    partial void Onid_hoidongChanged();
    partial void Onid_detaiChanging(System.Nullable<int> value);
    partial void Onid_detaiChanged();
    partial void Onid_khoaChanging(System.Nullable<int> value);
    partial void Onid_khoaChanged();
    #endregion
		
		public LichBaoVe()
		{
			this._DeTaiDoAn = default(EntityRef<DeTaiDoAn>);
			this._HoiDongBaoVe = default(EntityRef<HoiDongBaoVe>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lich", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_lich
		{
			get
			{
				return this._id_lich;
			}
			set
			{
				if ((this._id_lich != value))
				{
					this.Onid_lichChanging(value);
					this.SendPropertyChanging();
					this._id_lich = value;
					this.SendPropertyChanged("id_lich");
					this.Onid_lichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong", DbType="VarChar(50)")]
		public string phong
		{
			get
			{
				return this._phong;
			}
			set
			{
				if ((this._phong != value))
				{
					this.OnphongChanging(value);
					this.SendPropertyChanging();
					this._phong = value;
					this.SendPropertyChanged("phong");
					this.OnphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay", DbType="Date")]
		public System.Nullable<System.DateTime> ngay
		{
			get
			{
				return this._ngay;
			}
			set
			{
				if ((this._ngay != value))
				{
					this.OnngayChanging(value);
					this.SendPropertyChanging();
					this._ngay = value;
					this.SendPropertyChanged("ngay");
					this.OnngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="Time")]
		public System.Nullable<System.TimeSpan> gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this.OngioChanging(value);
					this.SendPropertyChanging();
					this._gio = value;
					this.SendPropertyChanged("gio");
					this.OngioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoidong", DbType="Int")]
		public System.Nullable<int> id_hoidong
		{
			get
			{
				return this._id_hoidong;
			}
			set
			{
				if ((this._id_hoidong != value))
				{
					if (this._HoiDongBaoVe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hoidongChanging(value);
					this.SendPropertyChanging();
					this._id_hoidong = value;
					this.SendPropertyChanged("id_hoidong");
					this.Onid_hoidongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detai", DbType="Int")]
		public System.Nullable<int> id_detai
		{
			get
			{
				return this._id_detai;
			}
			set
			{
				if ((this._id_detai != value))
				{
					if (this._DeTaiDoAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_detaiChanging(value);
					this.SendPropertyChanging();
					this._id_detai = value;
					this.SendPropertyChanged("id_detai");
					this.Onid_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khoa", DbType="Int")]
		public System.Nullable<int> id_khoa
		{
			get
			{
				return this._id_khoa;
			}
			set
			{
				if ((this._id_khoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khoaChanging(value);
					this.SendPropertyChanging();
					this._id_khoa = value;
					this.SendPropertyChanged("id_khoa");
					this.Onid_khoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTaiDoAn_LichBaoVe", Storage="_DeTaiDoAn", ThisKey="id_detai", OtherKey="id_detai", IsForeignKey=true)]
		public DeTaiDoAn DeTaiDoAn
		{
			get
			{
				return this._DeTaiDoAn.Entity;
			}
			set
			{
				DeTaiDoAn previousValue = this._DeTaiDoAn.Entity;
				if (((previousValue != value) 
							|| (this._DeTaiDoAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeTaiDoAn.Entity = null;
						previousValue.LichBaoVes.Remove(this);
					}
					this._DeTaiDoAn.Entity = value;
					if ((value != null))
					{
						value.LichBaoVes.Add(this);
						this._id_detai = value.id_detai;
					}
					else
					{
						this._id_detai = default(Nullable<int>);
					}
					this.SendPropertyChanged("DeTaiDoAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoiDongBaoVe_LichBaoVe", Storage="_HoiDongBaoVe", ThisKey="id_hoidong", OtherKey="id_hoidong", IsForeignKey=true)]
		public HoiDongBaoVe HoiDongBaoVe
		{
			get
			{
				return this._HoiDongBaoVe.Entity;
			}
			set
			{
				HoiDongBaoVe previousValue = this._HoiDongBaoVe.Entity;
				if (((previousValue != value) 
							|| (this._HoiDongBaoVe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoiDongBaoVe.Entity = null;
						previousValue.LichBaoVes.Remove(this);
					}
					this._HoiDongBaoVe.Entity = value;
					if ((value != null))
					{
						value.LichBaoVes.Add(this);
						this._id_hoidong = value.id_hoidong;
					}
					else
					{
						this._id_hoidong = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoiDongBaoVe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_LichBaoVe", Storage="_Khoa", ThisKey="id_khoa", OtherKey="id_khoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.LichBaoVes.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.LichBaoVes.Add(this);
						this._id_khoa = value.id_khoa;
					}
					else
					{
						this._id_khoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
